INSERT INTO LAB_WORK VALUES (1);
INSERT INTO LAB_WORK VALUES (2);
INSERT INTO LAB_WORK VALUES (3);
INSERT INTO LAB_WORK VALUES (4);

INSERT INTO STUDENT VALUES (10, 'Карпов Н.И.');
INSERT INTO STUDENT VALUES (11, 'Биглер П.П.');
INSERT INTO STUDENT VALUES (12, 'Куконен Е.И.');

INSERT INTO MARK VALUES ( 7, 10, 1);
INSERT INTO MARK VALUES ( 9, 11, 1);
INSERT INTO MARK VALUES ( 8, 12, 1);
INSERT INTO MARK VALUES ( 0, 10, 2);
INSERT INTO MARK VALUES ( 0, 11, 2);
INSERT INTO MARK VALUES ( 0, 12, 2);
INSERT INTO MARK VALUES ( 0, 10, 3);
INSERT INTO MARK VALUES ( 0, 11, 3);
INSERT INTO MARK VALUES ( 0, 12, 3);
INSERT INTO MARK VALUES ( 0, 10, 4);
INSERT INTO MARK VALUES ( 0, 11, 4);
INSERT INTO MARK VALUES ( 0, 12, 4);

INSERT INTO USR(USER_ID, USERNAME, PASS_HASH, ACTIVE, ROLES) VALUES (1, 'admin1', '$2a$10$nI/mVcA2sHAc.VPIbHfe0Ohf6.FuoVVjZcp/c0dXJDPQpjGv0TCwa', true, 'ROLE_ADMIN');
INSERT INTO USR(USER_ID, USERNAME, PASS_HASH, ACTIVE, ROLES) VALUES (2, 'admin2', '$2a$10$GZdjUEG5RtYOKcCC47/XVOD4B4UBcZU.VkOoxdjX2aSdRkpa081Jm', true, 'ROLE_ADMIN');
INSERT INTO USR(USER_ID, USERNAME, PASS_HASH, ACTIVE, ROLES) VALUES (3, 'user1', '$2a$10$S.O6UGn6AsbhlEzJ.DNYkerWF/z0iwQg46S.2ybxxlbZhI712DruG', true, 'ROLE_USER');